import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileSpreadsheet, Sparkles, Zap, Shield, CheckCircle, HelpCircle } from 'lucide-react';
import { useAuthStore } from '../store/authStore';
import { Helmet } from 'react-helmet-async';

const Home = () => {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const isLoggedIn = !!user?.token;
  const [isLoading, setIsLoading] = useState(false);

  // Updated login function with better parameters
  const handleGetStarted = () => {
    try {
      setIsLoading(true);
      // If already logged in, go to dashboard
      if (isLoggedIn) {
        navigate('/dashboard');
        return;
      }
      
      // Direct to Microsoft authentication - Updated with better parameters
      const redirectUrl = `${window.location.origin}/auth/callback`;
      
      // Store the current URL for potential redirect after login
      sessionStorage.setItem('authRedirectUrl', '/dashboard');
      
      // Generate a more secure nonce and state
      const nonce = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
      const state = Math.random().toString(36).substring(2, 15);
      
      // Store state for validation in callback
      sessionStorage.setItem('auth_state', state);
      
      // Define the B2C URL with all necessary parameters - updated with more explicit parameters
      const b2cUrl = `https://zarium.b2clogin.com/zarium.onmicrosoft.com/B2C_1_signup_signin/oauth2/v2.0/authorize?client_id=279cccfd-a2d6-4149-90d2-311cf5db1f35&response_type=id_token&redirect_uri=${encodeURIComponent(redirectUrl)}&response_mode=query&scope=openid%20profile%20email&state=${state}&nonce=${nonce}`;
      
      console.log(`Redirecting to: ${b2cUrl}`);
      
      // Redirect to B2C login page
      window.location.href = b2cUrl;
    } catch (error) {
      console.error('Navigation error:', error);
      setIsLoading(false);
    }
  };

  return (
    <>
      <Helmet>
        <title>Zarium | AI Excel Generator | Create Spreadsheets in Seconds</title>
        <meta name="description" content="Transform ideas into professional Excel spreadsheets with AI in seconds. Upload existing files or create new ones from scratch with Zarium." />
        {/* Other meta tags remain unchanged */}
      </Helmet>

      <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-white dark:from-gray-900 dark:to-gray-800">
        <div className="container mx-auto px-4 sm:px-6">
          
          {/* Hero Section */}
          <div className="pt-16 md:pt-24 pb-12 md:pb-20">
            <div className="text-center max-w-4xl mx-auto">
              <div className="inline-flex items-center justify-center px-4 py-2 mb-6 md:mb-8 rounded-full bg-emerald-100 dark:bg-emerald-900/50 text-emerald-800 dark:text-emerald-200 shadow-sm">
                <Sparkles className="h-4 w-4 mr-2" aria-hidden="true" />
                <span className="text-sm font-medium">Powered by Advanced AI</span>
              </div>
              <h1 className="text-3xl md:text-4xl font-bold mb-4 md:mb-6 text-emerald-900 dark:text-emerald-100 leading-tight">
                Excel Spreadsheets,<br />Generated by AI in Seconds
              </h1>
              <p className="text-base md:text-lg text-emerald-700 dark:text-emerald-300 mb-8 md:mb-10 leading-relaxed max-w-2xl mx-auto">
                Transform your ideas into professional Excel spreadsheets instantly.
                Just describe what you need, and watch the magic happen.
              </p>
              <div className="flex justify-center">
                <button
                  onClick={handleGetStarted}
                  disabled={isLoading}
                  className="px-8 py-3 rounded-lg text-base font-medium bg-emerald-800 dark:bg-emerald-700 text-white hover:bg-emerald-900 dark:hover:bg-emerald-600 transition-all shadow-sm hover:shadow-md disabled:opacity-70 disabled:cursor-not-allowed"
                  aria-label={isLoggedIn ? 'Go to Dashboard' : 'Get Started Free'}
                >
                  {isLoading ? 'Loading...' : (isLoggedIn ? 'Go to Dashboard' : 'Get Started Free')}
                </button>
              </div>
            </div>
          </div>

          {/* Features Section */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8 max-w-5xl mx-auto pb-12 md:pb-16">
            {[
              {
                icon: <Zap className="h-6 w-6" aria-hidden="true" />,
                title: "Instant Generation",
                description: "Get complete Excel spreadsheets created in seconds with advanced AI - saving you hours of manual work."
              },
              {
                icon: <FileSpreadsheet className="h-6 w-6" aria-hidden="true" />,
                title: "Advanced Visuals",
                description: "Create professional spreadsheets with 3D graphs, diagrams, custom formatting, and complex formulas."
              },
              {
                icon: <Shield className="h-6 w-6" aria-hidden="true" />,
                title: "Enhance Existing Files",
                description: "Upload your Excel files to clean, improve, analyze, or solve specific tasks with AI assistance."
              }
            ].map((feature, index) => (
              <div
                key={index}
                className="bg-white dark:bg-gray-800 p-6 md:p-8 rounded-2xl shadow-sm hover:shadow-md transition-all border border-emerald-100 dark:border-emerald-800 flex flex-col items-center text-center"
              >
                <div className="w-12 h-12 bg-emerald-100 dark:bg-emerald-900/50 rounded-xl flex items-center justify-center text-emerald-800 dark:text-emerald-200 mb-6">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold mb-4 text-emerald-900 dark:text-emerald-100">
                  {feature.title}
                </h3>
                <p className="text-emerald-700 dark:text-emerald-300 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
          
          {/* How It Works Section */}
          <div className="max-w-5xl mx-auto pb-16 md:pb-20">
            <h2 className="text-2xl md:text-3xl font-bold text-center mb-8 md:mb-12 text-emerald-900 dark:text-emerald-100">
              How Our AI Excel Generator Works
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {[
                {
                  step: "1",
                  title: "Describe or Upload",
                  description: "Either describe what you need in plain language or upload an existing Excel file you want to enhance."
                },
                {
                  step: "2",
                  title: "AI Creates Your Spreadsheet",
                  description: "Our advanced AI generates a complete Excel file in seconds with formulas, 3D graphs, and professional formatting."
                },
                {
                  step: "3",
                  title: "Preview and Download",
                  description: "Review your AI-generated Excel file and download it with a subscription. Free trials can preview the results."
                }
              ].map((step, index) => (
                <div key={index} className="flex flex-col items-center text-center">
                  <div className="w-12 h-12 bg-emerald-700 dark:bg-emerald-600 rounded-full flex items-center justify-center text-white font-bold mb-6" aria-hidden="true">
                    {step.step}
                  </div>
                  <h3 className="text-xl font-semibold mb-4 text-emerald-900 dark:text-emerald-100">
                    {step.title}
                  </h3>
                  <p className="text-emerald-700 dark:text-emerald-300 leading-relaxed">
                    {step.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
          
          {/* Use Cases Section */}
          <div className="bg-emerald-50 dark:bg-gray-800/50 py-12 md:py-16 -mx-4 sm:-mx-6 px-4 sm:px-6 mb-16 md:mb-20">
            <div className="max-w-5xl mx-auto">
              <h2 className="text-2xl md:text-3xl font-bold text-center mb-8 md:mb-12 text-emerald-900 dark:text-emerald-100">
                Excel Spreadsheets You Can Generate
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
                {[
                  "Financial Models with 3D Charts",
                  "Project Trackers & Gantt Charts",
                  "Inventory Systems & Analysis",
                  "Budget Templates with Forecasting",
                  "Data Analysis & Visualization",
                  "Invoice & Accounting Systems",
                  "Schedule & Resource Planners",
                  "Interactive KPI Dashboards",
                  "Custom Excel File Enhancement"
                ].map((useCase, index) => (
                  <div key={index} className="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-sm flex items-center">
                    <CheckCircle className="h-5 w-5 text-emerald-600 dark:text-emerald-400 mr-3 flex-shrink-0" aria-hidden="true" />
                    <span className="text-emerald-800 dark:text-emerald-200 font-medium">{useCase}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
          
          {/* FAQ Section */}
          <div className="max-w-4xl mx-auto pb-16 md:pb-24">
            <h2 className="text-2xl md:text-3xl font-bold text-center mb-8 md:mb-12 text-emerald-900 dark:text-emerald-100">
              Frequently Asked Questions
            </h2>
            <div className="space-y-4 md:space-y-6">
              {[
                {
                  question: "How quickly can Zarium generate an Excel spreadsheet?",
                  answer: "Zarium creates complete, professional Excel spreadsheets in seconds based on your input. Just describe what you need, and our AI will generate an entire spreadsheet with all necessary formulas, formatting, and visualizations - saving you hours of manual work."
                },
                {
                  question: "What types of Excel spreadsheets can Zarium generate?",
                  answer: "Zarium can generate virtually any type of Excel spreadsheet, including financial models, project trackers, inventory systems, budgets, invoices, and data analysis templates. Our AI can create advanced 3D graphs, complex diagrams, and interactive dashboards within these spreadsheets."
                },
                {
                  question: "Is Zarium easy to use if I'm not an Excel expert?",
                  answer: "Absolutely! Zarium is designed to be extremely user-friendly. You don't need Excel expertise - simply describe what you need in plain language, and our AI handles all the complex formula creation, chart building, and formatting. For example, you can type 'Create a monthly budget tracker with expense categories and a 3D chart showing spending trends' and Zarium will build it for you."
                },
                {
                  question: "Can I upload my existing Excel files?",
                  answer: "Yes! Zarium can work with your existing Excel files in multiple ways: clean up messy data, enhance formatting, add new features like charts or pivot tables, improve existing formulas, analyze the data to find insights, or solve specific problems. You can ask things like 'Add a 3D visualization of my sales data' or 'Fix the broken formulas in column D' or 'Analyze this data and tell me the key trends.'"
                },
                {
                  question: "Can I customize the Excel files after they're generated?",
                  answer: "Absolutely! All Excel files generated by Zarium are standard .xlsx files that you can open and modify in Microsoft Excel, Google Sheets, or any compatible spreadsheet program."
                },
                {
                  question: "Is Zarium's AI Excel generator free to use?",
                  answer: "Zarium offers a free trial with limited tokens that lets you test the service and preview generated spreadsheets. To download files and access the full functionality, you'll need a subscription. Our paid plans offer different token amounts to suit various usage needs."
                }
              ].map((faq, index) => (
                <div key={index} className="bg-white dark:bg-gray-800 p-5 md:p-6 rounded-xl shadow-sm border border-emerald-100 dark:border-emerald-800">
                  <h3 className="text-lg font-semibold mb-3 flex items-start text-emerald-900 dark:text-emerald-100">
                    <HelpCircle className="h-5 w-5 text-emerald-600 dark:text-emerald-400 mr-2 mt-0.5 flex-shrink-0" aria-hidden="true" />
                    {faq.question}
                  </h3>
                  <p className="text-emerald-700 dark:text-emerald-300 leading-relaxed ml-7">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>
          
          {/* CTA Section - Update to use the same direct authentication */}
          <div className="bg-emerald-700 dark:bg-emerald-800 text-white -mx-4 sm:-mx-6 px-4 sm:px-6 py-12 md:py-16 mb-8 md:mb-12 rounded-lg md:rounded-xl">
            <div className="max-w-4xl mx-auto text-center">
              <h2 className="text-2xl md:text-3xl font-bold mb-4 md:mb-6">
                Start Generating Excel Spreadsheets Today
              </h2>
              <p className="text-base md:text-lg text-emerald-100 dark:text-emerald-200 mb-6 md:mb-8 max-w-2xl mx-auto">
                Join professionals who save hours every week with Zarium's AI Excel generator. Create complete spreadsheets in seconds or enhance your existing Excel files.
              </p>
              <button
                onClick={handleGetStarted}
                disabled={isLoading}
                className="px-8 py-3 rounded-lg text-base font-medium bg-white text-emerald-900 hover:bg-emerald-100 transition-all shadow-sm hover:shadow-md disabled:opacity-70 disabled:cursor-not-allowed"
                aria-label={isLoggedIn ? 'Go to Dashboard' : 'Get Started Free'}
              >
                {isLoading ? 'Loading...' : (isLoggedIn ? 'Go to Dashboard' : 'Get Started Free')}
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;