import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { FileSpreadsheet, Sparkles, Zap, Shield } from 'lucide-react';
import { useAuthStore } from '../store/authStore';

export default function Home() {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const isLoggedIn = !!user?.token;

  const handleGetStarted = () => {
    if (isLoggedIn) {
      navigate('/dashboard');
    } else {
      navigate('/pricing');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-white dark:from-gray-900 dark:to-gray-800">
      <div className="container mx-auto px-6">
        
        <div className="pt-24 pb-20">
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center justify-center px-4 py-2 mb-8 rounded-full bg-emerald-100 dark:bg-emerald-900/50 text-emerald-800 dark:text-emerald-200 shadow-sm">
              <Sparkles className="h-4 w-4 mr-2" />
              <span className="text-sm font-medium">Powered by Advanced AI</span>
            </div>
            <h1 className="text-4xl font-bold mb-6 text-emerald-900 dark:text-emerald-100 leading-tight">
              Excel Spreadsheets,<br />Generated by AI
            </h1>
            <p className="text-lg text-emerald-700 dark:text-emerald-300 mb-10 leading-relaxed max-w-2xl mx-auto">
              Transform your ideas into professional Excel spreadsheets instantly.
              Just describe what you need, and watch the magic happen.
            </p>
            <div className="flex justify-center gap-4">
              <button
                onClick={handleGetStarted}
                className="px-8 py-3 rounded-lg text-base font-medium bg-emerald-800 dark:bg-emerald-700 text-white hover:bg-emerald-900 dark:hover:bg-emerald-600 transition-all shadow-sm hover:shadow-md"
              >
                {isLoggedIn ? 'Go to Dashboard' : 'Start Generating'}
              </button>
              
              
              {!isLoggedIn && (
                <button
                onClick={() => navigate('/register', { 
                  state: { 
                    selectedPlan: 'Demo', 
                    isDemo: true,
                    demoPriceId: 'price_1R2isCB9ONdEOi8LoDv9vBTN'   // Send med pris-ID for Demo
                  } 
                })}
                className="px-8 py-3 rounded-lg text-base font-medium bg-white dark:bg-gray-800 text-emerald-800 dark:text-emerald-200 hover:bg-emerald-50 dark:hover:bg-gray-700 transition-all shadow-sm hover:shadow-md border border-emerald-200 dark:border-emerald-800 flex items-center gap-2"
              >
                <Sparkles className="h-5 w-5" />
                Try Demo
              </button>
              )}
            </div>
          </div>
        </div>

        
        <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto pb-24">
          {[
            {
              icon: <Zap className="h-6 w-6" />,
              title: "Instant Generation",
              description: "Get your Excel spreadsheets created in seconds with our advanced AI technology."
            },
            {
              icon: <FileSpreadsheet className="h-6 w-6" />,
              title: "Excel Expertise",
              description: "Professional spreadsheets with proper formatting, formulas, and data validation."
            },
            {
              icon: <Shield className="h-6 w-6" />,
              title: "Secure & Private",
              description: "Your data and generated spreadsheets are always encrypted and secure."
            }
          ].map((feature, index) => (
            <div
              key={index}
              className="bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-sm hover:shadow-md transition-all border border-emerald-100 dark:border-emerald-800 flex flex-col items-center text-center"
            >
              <div className="w-12 h-12 bg-emerald-100 dark:bg-emerald-900/50 rounded-xl flex items-center justify-center text-emerald-800 dark:text-emerald-200 mb-6">
                {feature.icon}
              </div>
              <h3 className="text-xl font-semibold mb-4 text-emerald-900 dark:text-emerald-100">
                {feature.title}
              </h3>
              <p className="text-emerald-700 dark:text-emerald-300 leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}